# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

primary: &primary
  <<: *default
  database: data/<%= Rails.env %>_rails_hotwire.sqlite3

cache: &cache
  <<: *default
  migrations_paths: db/cache_migrate
  database: data/<%= Rails.env %>_rails_hotwire_cache.sqlite3

queue: &queue
  <<: *default
  migrations_paths: db/queue_migrate
  database: data/<%= Rails.env %>_rails_hotwire_queue.sqlite3

development:
  primary: *primary
  cache: *cache
  queue: *queue

test:
  primary: *primary
  cache: *cache
  queue: *queue

production:
  primary: *primary
  cache: *cache
  queue: *queue
