# frozen_string_literal: true

source 'https://rubygems.org'

gem 'bootsnap', require: false
gem 'mission_control-jobs'
gem 'propshaft'
gem 'puma'
gem 'rails'
gem 'solid_cache'
gem 'solid_queue'
gem 'sqlite3'

gem 'pagy'
gem 'stimulus-rails'
gem 'turbo-rails'
gem 'view_component'
gem 'vite_rails'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'
  gem 'rubocop'
  gem 'rubocop-performance'
  gem 'rubocop-rails'
  gem 'rubocop-rspec'

  gem 'bcrypt_pbkdf'
  gem 'ed25519'
  gem 'kamal'
end

group :development do
  gem 'listen', '~> 3.3'
end
