# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

gem 'puma'
gem 'rails'
gem 'sqlite3'
gem 'bootsnap', require: false

gem 'pagy'
gem 'stimulus-rails'
gem 'turbo-rails'
gem 'view_component'
gem 'vite_rails'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'
  gem 'rubocop'
  gem 'rubocop-performance'
  gem 'rubocop-rails'
  gem 'rubocop-rspec'

  gem 'bcrypt_pbkdf'
  gem 'ed25519'
  gem 'kamal'
end

group :development do
  gem 'listen', '~> 3.3'
end
