# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby file: '.ruby-version'

gem 'puma', '~> 4'
gem 'rails', '< 7.2'
gem 'sqlite3'

gem 'importmap-rails'
gem 'pagy'
gem 'slim-rails'
gem 'sprockets-rails'
gem 'stimulus-rails'
gem 'turbo-rails'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'
  gem 'rubocop'
  gem 'rubocop-performance'
  gem 'rubocop-rails'
  gem 'rubocop-rspec'

  gem 'bcrypt_pbkdf'
  gem 'capistrano', require: false
  gem 'capistrano3-delayed-job', require: false
  gem 'capistrano3-puma', '~> 4.0', require: false
  gem 'capistrano-rails', require: false
  gem 'capistrano-rvm', require: false
  gem 'ed25519'
end

group :development do
  gem 'listen', '~> 3.3'
end
